### ISSUE TITLE
意外的异常

### ISSUE THREAD

**Issue by Chlorie** [richardchien/coolq-cpp-sdk#1]
在调用cq::api::get_group_member_info时总会抛出异常

[0xE06D7363] 发生错误
EAX=0611E180 EBX=00000000 ECX=00000003
EDX=00000000 ESI=0648B210 EDI=0611E21C
EIP=76E9DB52 ESP=0611E180 EBP=0611E1DC
CS=23 SS=2B DS=2B ES=2B FS=53 GS=2B

[KERNELBASE.dll](0x76D90000)->RaiseException(0x10DAF0)+0x62=0x76E9DB52
[me.cqp.chlorie.tairitsu_bot.dll](0x06120000)->_CxxThrowException(0x18A7B0)+0xA3=0x062AA853
[me.cqp.chlorie.tairitsu_bot.dll](0x06120000)->cq::api::get_group_member_info(0xA0B40)+0xBC=0x061C0BFC
[me.cqp.chlorie.tairitsu_bot.dll](0x06120000)->is_admin(0xA7CB0)+0x44=0x061C7CF4
[me.cqp.chlorie.tairitsu_bot.dll](0x06120000)->handle_repeats(0xA7D60)+0x3B2=0x061C8112
[me.cqp.chlorie.tairitsu_bot.dll](0x06120000)-><lambda_8f8429b58a7d5a5c7720a4b16465737f>::operator()(0xA70E0)+0x17=0x061C70F7
[me.cqp.chlorie.tairitsu_bot.dll](0x06120000)->std::_Invoker_functor::_Call<<lambda_8f8429b58a7d5a5c7720a4b16465737f> &,cq::event::GroupMessageEvent const &>(0x9B2D0)+0x2F=0x061BB2FF
[me.cqp.chlorie.tairitsu_bot.dll](0x06120000)->std::invoke<<lambda_8f8429b58a7d5a5c7720a4b16465737f> &,cq::event::GroupMessageEvent const &>(0x9F030)+0x22=0x061BF052
[me.cqp.chlorie.tairitsu_bot.dll](0x06120000)->std::_Invoker_ret<void,1>::_Call<<lambda_8f8429b58a7d5a5c7720a4b16465737f> &,cq::event::GroupMessageEvent const &>(0x9B2A0)+0x22=0x061BB2C2
[me.cqp.chlorie.tairitsu_bot.dll](0x06120000)->std::_Func_impl_no_alloc<<lambda_8f8429b58a7d5a5c7720a4b16465737f>,void,cq::event::GroupMessageEvent const &>::_Do_call(0x43BD0)+0x27=0x06163BF7
[me.cqp.chlorie.tairitsu_bot.dll](0x06120000)->std::_Func_class<void,cq::event::GroupMessageEvent const &>::operator()(0x413F0)+0x54=0x06161444
[me.cqp.chlorie.tairitsu_bot.dll](0x06120000)->cq::utils::call_if_valid<cq::event::GroupMessageEvent const &,cq::event::GroupMessageEvent &>(0x398E0)+0x4D=0x0615992D
[me.cqp.chlorie.tairitsu_bot.dll](0x06120000)->cq_event_group_msg(0x39530)+0x31C=0x0615984C
[CQP.dll](0x10000000)+0x1C95A3=0x101C95A3
[CQP.dll](0x10000000)+0x1C962D=0x101C962D
[CQP.dll](0x10000000)+0x18F9A=0x10018F9A
[CQP.dll](0x10000000)+0x884A6=0x100884A6
[CQP.dll](0x10000000)+0x85FA7=0x10085FA7
[CQP.dll](0x10000000)+0x8DDE7=0x1008DDE7
[ntdll.dll](0x776D0000)->RtlValidSecurityDescriptor(0x62ED0)+0x11A=0x77732FEA
[ntdll.dll](0x776D0000)->RtlValidSecurityDescriptor(0x62ED0)+0xEA=0x77732FBA

若catch该异常则一直会输出failed to call coolq api
这里为什么会调用失败呢……

**Comment by stdrc** [comment]
他抛出的是 cq::ApiError 吗
Chlorie <notifications@github.com>于2018年7月10日 周二19:38写道：

**Comment by Chlorie** [comment]
是的
但是现在莫名其妙地又好了，我不知道到底是什么情况……
总之谢谢了
打扰了

**Comment by stdrc** [comment]
抛出 ApiError 是故意的，你可以看下函数实现，你之前抛出而现在又不抛出是因为之前获取失败了现在获取成功了，这个 exception 需要
catch 的，获取失败一般可能是酷 Q 缓存出了问题
Chlorie <notifications@github.com>于2018年7月11日 周三00:27写道：

**Comment by Chlorie** [comment]
好的，谢谢您
