### ISSUE TITLE
我电脑上有vs2017，怎么用vs打开示例工程

### ISSUE THREAD

**Issue by shimachao** [richardchien/coolq-cpp-sdk#10]
只能打开单个源码文件吗？能打开工程吗

**Comment by stdrc** [comment]
vs 和 vscode 都可以通过“打开文件夹”的方式打开项目，由于是个 cmake 项目，并没有 vs 的工程配置文件，直接打开文件夹就好

shimachao <notifications@github.com> 于 2019年7月4日周四 15:20写道：
