### ISSUE TITLE
demo突然不能编译了，error C2039: “opertion”: 不是“cq::event::GroupAdminEvent”的成员

### ISSUE THREAD

**Issue by shimachao** [richardchien/coolq-cpp-sdk#11]
PS D:\my-awesome-app> powershell .\scripts\build.ps1 Debug
CMake 路径：cmake.exe
正在使用 CMake 构建项目……
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
版权所有(C) Microsoft Corporation。保留所有权利。

  event.cpp
D:\my-awesome-app\src\cqsdk\event.cpp(128): error C2039: “opertion”: 不是“cq::event::GroupAdminEvent”的成员 [D:\my-awesome-a
pp\build\Debug\app.vcxproj]
  d:\my-awesome-app\src\cqsdk\./event.h(92): note: 参见“cq::event::GroupAdminEvent”的声明
CMake 构建失败

**Comment by stdrc** [comment]
应该是你不小心改了某个单词，重新下载一下 sdk 代码就好
