### ISSUE TITLE
有文档吗

### ISSUE THREAD

**Issue by lzxZz** [richardchien/coolq-cpp-sdk#14]
什么时候能加上文档个注释啊

**Comment by stdrc** [comment]
文档暂时没有，目前大概需要顺着头文件找进去看源码，不过以后应该会加上，需要些时间

**Comment by stdrc** [comment]
欢迎来尝试新版 C++ SDK：[cqmoe/cqcppsdk](https://github.com/cqmoe/cqcppsdk)，新版有文档了！
