### ISSUE TITLE
无法构建 Vcpkg

### ISSUE THREAD

**Issue by Kelvely** [richardchien/coolq-cpp-sdk#6]
在构建 Vcpkg 过程中出错。
日志如下（powershell ./scripts/prepare.ps1 > prepare.log）
[prepare.log](https://github.com/richardchien/coolq-cpp-sdk/files/2982929/prepare.log)

**Comment by stdrc** [comment]
可能你没有安装正确的 VC++ 工具集，截个 VS Installer 的安装了的组件图看看？

**Comment by Kelvely** [comment]
使用了 Visual Studio Community 2017 15.6.6
![001{7 C 0 YIMDI~6JB`GKC](https://user-images.githubusercontent.com/22560533/54605101-71af5d00-4a83-11e9-8096-48cf7cd916d8.png)

**Comment by Kelvely** [comment]
通过更新至 Visual Studio Community 2017 至 15.9.9 解决了这个问题。
