### ISSUE TITLE
about unofficial-iconv

### ISSUE THREAD

**Issue by Moying-moe** [richardchien/coolq-cpp-sdk#9]
错误信息：

CMake 路径：cmake.exe
正在使用 CMake 生成构建目录……
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
-- cotire 1.8.0 loaded.
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:266 (_find_package):
  Could not find a package configuration file provided by "unofficial-iconv"
  with any of the following names:

    unofficial-iconvConfig.cmake
    unofficial-iconv-config.cmake

  Add the installation prefix of "unofficial-iconv" to CMAKE_PREFIX_PATH or
  set "unofficial-iconv_DIR" to a directory containing one of the above
  files.  If "unofficial-iconv" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:28 (find_package)

-- Configuring incomplete, errors occurred!
See also "./build/Debug/CMakeFiles/CMakeOutput.log".
CMake 生成失败

**Comment by Moying-moe** [comment]
ps: while running `generate.ps1`

**Comment by stdrc** [comment]
`prepare.ps1` 运行成功了吗

**Comment by Moying-moe** [comment]
似乎有报错，我重新执行一遍试试看

**Comment by Moying-moe** [comment]
ok 重新安装依赖库后生成正常
